### ISSUE TITLE
composer create-project carlalexander/bedrock-pantheon-circleci not working

### ISSUE THREAD

**Issue by jonrrivera** [carlalexander/bedrock-pantheon-circleci#2]
I appreciate your help with this template. When I run the composer command in my terminal, it shows:

[InvalidArgumentException]                                                             
  Could not find package carlalexander/bedrock-pantheon-circleci with stability stable.

is this not on packagist anymore? if not, am I good by just cloning this repo? let me know, thanks!

**Comment by carlalexander** [comment]
You're right! I hadn't done it. Can you try now?

**Comment by jonrrivera** [comment]
@carlalexander ah still having problems

<img width="643" alt="Screen Shot 2020-03-30 at 10 40 39 PM" src="https://user-images.githubusercontent.com/18686388/77981285-80a42e80-72d7-11ea-9a0f-669198566cb1.png">

**Comment by jonrrivera** [comment]
@carlalexander ah still giving the same Could not find package carlalexander/bedrock-pantheon-circleci with stability stable error. I even updated my composer to 1.10.1

I see that the package is now available on [packagist](https://packagist.org/packages/carlalexander/bedrock-pantheon-circleci) tho

thanks for the quick response! hope to get this fired up soon.

**Comment by carlalexander** [comment]
Sorry, for the delay, I tagged a version which should solve the issue

**Comment by jonrrivera** [comment]
man unfortunately I am still getting the same error. Am I just better of cloning this repository? 
thanks !

**Comment by carlalexander** [comment]
Finally, found what was tripping Composer. Should work now. Sorry, it took so long!

<img width="681" alt="image" src="https://user-images.githubusercontent.com/654684/78398080-6eb8d900-75c0-11ea-9d5a-62729cd43d67.png">

**Comment by jonrrivera** [comment]
working now! thanks so much!
